name: mdntls
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.7
  google_fonts: ^2.3.2
  get_it: ^7.2.0
  flutter_riverpod: ^1.0.3
  fluttertoast: ^8.0.9
  curved_navigation_bar: ^1.0.3
  intl_phone_number_input: ^0.7.0+2
  modal_bottom_sheet: ^2.0.1
  image_picker: ^0.8.5+3
  qr_code_scanner: ^0.7.0
  pretty_qr_code: ^2.0.2
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/test_images/